package utils

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// GetHostname returns the system hostname
func GetHostname() string {
	name, err := os.Hostname()
	if err != nil {
		return "localhost"
	}
	return name
}

// GetBaseDir returns the directory where the binary is located, or the source file directory
// if running via 'go run'. It provides a stable anchor for logs and config files.
func GetBaseDir() string {
	exePath, err := os.Executable()
	if err == nil {
		exeDir := filepath.Dir(exePath)
		// If not in a temporary go-build directory, use the executable's directory
		if !strings.Contains(exeDir, "go-build") && !strings.Contains(exeDir, "T/go-build") {
			return exeDir
		}
	}

	// Fallback/Smart Resolve for 'go run': find the directory of the caller's main.go
	// We skip all known platform libraries to find the actual service entry point.
	for i := 1; i < 25; i++ {
		_, file, _, ok := runtime.Caller(i)
		if !ok {
			break
		}

		// Skip list: stdlib and platform internal libs
		skip := false
		libsToSkip := []string{
			"runtime/", "reflect/", "testing/",
			"distributed-config", "microservice-toolbox", "universal-logger",
			"flexible-logger", "safe-socket", "message-serializers",
			"<autogenerated>",
		}
		for _, lib := range libsToSkip {
			if strings.Contains(file, lib) {
				skip = true
				break
			}
		}

		if !skip && file != "" {
			return filepath.Dir(file)
		}
	}

	// Final fallback: Current Working Directory
	if wd, err := os.Getwd(); err == nil {
		return wd
	}
	return "."
}
