# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: teleremote.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'teleremote.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10teleremote.proto\x12\nteleremote\"\xc2\x01\n\x10\x43omponentMessage\x12\x16\n\x0e\x63omponent_name\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x30\n\x0cregistration\x18\x04 \x01(\x0b\x32\x18.teleremote.RegistrationH\x00\x12\x13\n\ttelemetry\x18\x05 \x01(\tH\x00\x12(\n\x04qmsg\x18\x06 \x01(\x0b\x32\x18.teleremote.QueueMessageH\x00\x42\t\n\x07payload\"!\n\x0cRegistration\x12\x11\n\tmenu_json\x18\x01 \x01(\t\"y\n\x0cQueueMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x11\n\tfrom_addr\x18\x03 \x01(\t\x12\x0f\n\x07to_addr\x18\x04 \x01(\t\x12\x11\n\x04\x61\x63kw\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x08priority\x18\x06 \x01(\x08\x42\x07\n\x05_ackw\"\xd7\x01\n\nBotCommand\x12\x38\n\x0c\x63ommand_type\x18\x01 \x01(\x0e\x32\".teleremote.BotCommand.CommandType\x12\x16\n\x0e\x63ustom_payload\x18\x02 \x01(\t\x12\r\n\x05input\x18\x03 \x01(\t\"h\n\x0b\x43ommandType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tPOWER_OFF\x10\x01\x12\x17\n\x13\x43LOSE_ALL_POSITIONS\x10\x02\x12\x10\n\x0cREFRESH_MENU\x10\x03\x12\x12\n\x0e\x43USTOM_COMMAND\x10\x63\x32X\n\x11TeleRemoteService\x12\x43\n\x07\x43onnect\x12\x1c.teleremote.ComponentMessage\x1a\x16.teleremote.BotCommand(\x01\x30\x01\x42SZQgithub.com/Bastien-Antigravity/microservice-toolbox/go/pkg/teleremote/grpc_clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'teleremote_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZQgithub.com/Bastien-Antigravity/microservice-toolbox/go/pkg/teleremote/grpc_client'
  _globals['_COMPONENTMESSAGE']._serialized_start=33
  _globals['_COMPONENTMESSAGE']._serialized_end=227
  _globals['_REGISTRATION']._serialized_start=229
  _globals['_REGISTRATION']._serialized_end=262
  _globals['_QUEUEMESSAGE']._serialized_start=264
  _globals['_QUEUEMESSAGE']._serialized_end=385
  _globals['_BOTCOMMAND']._serialized_start=388
  _globals['_BOTCOMMAND']._serialized_end=603
  _globals['_BOTCOMMAND_COMMANDTYPE']._serialized_start=499
  _globals['_BOTCOMMAND_COMMANDTYPE']._serialized_end=603
  _globals['_TELEREMOTESERVICE']._serialized_start=605
  _globals['_TELEREMOTESERVICE']._serialized_end=693
# @@protoc_insertion_point(module_scope)
